run:
	./run --gui

run-no-gui:
	./run

build:
	mvn clean package

build-s:
	mvn clean package -Dmaven.test.skip=true

set-up-react:
	cd frontend && npm install

react:
	cd frontend && npm start

site:
	mvn site